export default Object.freeze({
  WELCOME_SCREEN: "WelcomeScreen",
  LOGIN_SCREEN: "LoginScreen",
  REGISTER_SCREEN: "RegisterScreen",
  AUTH_NAVIGATION: "Auth Nav",
  TAB_NAVIGATION: "Tab Nav",
  HOME_SCREEN: "Home Screen",
  ACCOUNT_SCREEN: "Account Screen",
  SEARCH_SCREEN: "Seach Screen",
  PROFILE_SCREEN: "Profile Screen",
  USER_NAVIGATION: "User nav",
  ORDERS_HISTORY_SCREEN: "Orders Screen",
  ORDERS_DETAIL_SCREEN: "OrderDetail Screen",
  PENDING_ORDERS_SCREEN: "Pending Screen",
  TRACK_DELIVERY_SCREEN: "TrackDelivery Screen",
  ORDER_NAVIGATION: "Order Nav",
  ORDER_SCREEN: "Order Screen",
  CHECHOUT_SCREEN: "Checkout Screen",
  TRANSACTIONS_SCREEN: "Transactions Screen",
  PROFILE_VIEW_SCREEN: "Profile view Screen",
  PROGRAM_DETAIL_SCREEN: "Programe Screen",
  REWARD_DETAIL_SCREEN: "Reward Screen",
  LOYALTY_POINTS_SCREEN: "LoyaltyPoints Screen",
  USER_TRANSFER_REQUESTS_SCREEN: "UserTransfer Screen",
  TRANSFER_DETAIL_SCREEN: "UserTransferdDetail Screen",
  ACTION_MENU_SCREEN: "Menu Screen",
  FORMS_NAVIGATION: "Forms Nav",
  FORMS_ACCOUNT_FORM: "Accounts Form",
  FORMS_PROFILE_FORM: "Profile Form",
  FORMS_NEXT_OF_KEEN_FORM: "NextOfKeen Form",
  FORMS_REDEEM_FORM: "Redeem Form",
  FORMS_ACCOUNT_VERIFICATION_FORM: "Verification Form",
  FORMS_CHANGE_PASSWORD_FORM: "Change password Form",
  FORMS_REQUEST_TRANFER_FORM: "RequestTransfer Form",
  DASHBOARD_NAVIGATION: "Dashboard Nav",
  DASHBOARD_SCREEN: "Dashboard Screen",
  USER_FIND_ACCOUNT_SCREEN: "Find Account Screen",
  USER_APPOINTMENTS_SCREEN: "Appointments Screen",
  USER_PRESCRIPTIONS_SCREEN: "Prescriptions Screen",
  USER_SETTINGS_SCREEN: "Settings Screen",
  ORDER_AGENT_DELIVERY_SCREEN: "Delivery Screen",
  ORDER_AGENT_DELIVERY_ROUTE_SCREEN: "DeliveryRoute Screen",
  TAB_AGENT_HOME_SCREEN: "Agent Home",
  USER_PROGRAM_DETAIL_SCREEN: "Programe Detetailed screen",
});
